[options]

; ============================================================
; ODOO 19 - SICPRO ERP
; Debian 13 / Python 3.13 / PostgreSQL 17
; 16 GB RAM / 4 vCPU
; ============================================================

; -----------------------------
; SEGURIDAD
; -----------------------------

admin_passwd = PASSWORD_ADMIN

; -----------------------------
; NGINX / PROXY
; -----------------------------

proxy_mode = True

; -----------------------------
; PostgreSQL
; -----------------------------

db_host = 127.0.0.1
db_port = 5432
db_user = odoo
db_password = PASSWORD_POSTGRESQL
db_maxconn = 10
db_sslmode = prefer

; Instancia de una sola base
db_name = sicproerp
dbfilter = ^sicproerp\$
list_db = False

; -----------------------------
; Directorios
; -----------------------------

data_dir = /opt/odoo/sicproerp-data/data

addons_path = /opt/odoo/sicproerp/odoo/addons,/opt/odoo/sicproerp/sicpro_app

; -----------------------------
; Logging
; -----------------------------

logfile = /opt/odoo/sicproerp-data/log/odoo/sicproerp.log
log_level = warn
log_handler = :INFO
logrotate = False

; -----------------------------
; HTTP / WebSocket
; -----------------------------

http_interface = 127.0.0.1
http_port = 8069
gevent_port = 8072

; -----------------------------
; Workers
; -----------------------------

workers = 5
max_cron_threads = 1

; -----------------------------
; Límites de recursos
; -----------------------------

limit_memory_soft = 1610612736
limit_memory_hard = 2147483648

limit_time_cpu = 600
limit_time_real = 1200
limit_time_real_cron = 1800
limit_request = 8192

; -----------------------------
; Módulos globales
; -----------------------------

server_wide_modules = base,web

; -----------------------------
; Zona horaria
; -----------------------------

timezone = America/Havana
