# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Servicios Internos',
    'version': '1.0.0',
    # Estados (Desarrollo o Producción) Desarrollo: Store o actualiza Producción: Store avisa de nueva actualización
    'estado': 'Desarrollo',
    'category': 'Trabajadores',
    'sequence': 2,
    'summary': "Esta aplicación se encargará del control de los servicios mobiles y de datos asignado a los "
               "trabajadores",
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'price': 0,
    'currency': 'CUP',
    'company': 'División de Proyectos y Ejecución de Obras',
    'website': 'https://www.facebook.com/dannyroses.oficial/',
    'license': 'AGPL-3',
    # 'external_dependencies': {'python': ['nombre del paquete', 'nombre del paquete']},
    'depends': [
        'nucleo_sicpro_erp',
        'sicpro_app_administracion',
        'sicpro_app_trabajadores',
        'base',
    ],
    'data': ['security/servicios_Internos.xml',
             'security/ir.model.access.csv',
             'data/plantillas_correo_data.xml',
             'data/ir_cron_data.xml',
             'informes/informe_anexo1_views.xml',
             'informes/informe_anexo2_views.xml',
             'informes/informe_compromiso_nauta_views.xml',
             'informes/informe_planilla_unica_views.xml',
             'views/interno_lineas_views.xml',
             'views/interno_fijos_views.xml',
             'views/interno_nauta_views.xml',
             'views/interno_correos_views.xml',
             'views/interno_trabajadores_views.xml',
             'views/interno_solicitudes_observaciones_views.xml',
             'views/interno_solicitudes_views.xml',

             'views/interno_menu_views.xml',
             ],
    'assets': {
        'web.assets_backend': [],
        'web.assets_qweb': [],
        'web.report_assets_common': [],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_check',
    # 'post_init_hook': 'post_init_hook',
    # 'uninstall_hook': 'uninstall_hook',,
}
