# -*- coding: utf-8 -*-


import logging
from itertools import chain
from dateutil.relativedelta import relativedelta

from odoo.exceptions import UserError, ValidationError
from odoo.http import request
from odoo import models, fields, api, http, _

try:
    import httpagentparser
except ImportError:
    pass

_logger = logging.getLogger(__name__)
USER_PRIVATE_FIELDS = ['password']
concat = chain.from_iterable


class LoginUsuarios(models.Model):
    _inherit = 'res.users'

    @api.model
    def _check_credentials(self, password, user_agent_env):
        result = super(LoginUsuarios, self)._check_credentials(password,
                                                               user_agent_env)
        agent = request.httprequest.environ.get('HTTP_USER_AGENT')
        agent_details = httpagentparser.detect(agent)
        try:
            # Es necesario para errores al detectar sistemas operativos
            # como android
            sistema_operativo = agent_details['os']['name']
        except:
            sistema_operativo = 'SO Móvil'

        navegador_web = agent_details['browser']['name']
        ip_address = request.httprequest.environ['REMOTE_ADDR']
        vals = {'name': self.name, 'ip_address': ip_address,
                'navegador_web': navegador_web,
                'sistema_operativo': sistema_operativo, }
        self.env['sicpro.modulo.registro.usuarios'].sudo().create(vals)

        # Configuración para el envío del correo
        url = http.request.env['ir.config_parameter'].get_param('web.base.url')

        # busco los usuarios con permisos a recibir los correos de alerta
        user_envio = request.env['res.users'].sudo().search(
            [('groups_id', 'in',  self.env.ref('sicpro_app_administracion.grupo_app_administracion_notificaciones').id)])


        for data in user_envio:
            fecha1 = fields.Date.context_today(self) - relativedelta(hours=5)
            fecha = fecha1.strftime("%d-%m-%Y %H:%M:%S")
            template_obj = request.env['mail.mail']
            message_body = '<table style="padding-top:16px;background-color: #F1F1F1; font-family:Verdana, Arial,sans-serif; color: #454748; width: 100%; border-collapse:separate;" cellspacing="0" cellpadding="0" border="0"><tbody><tr><td align="center"> ' \
                           '<table style="padding:16px;background-color: white; color: #454748; border-collapse:separate;" width="590" cellspacing="0" cellpadding="0" border="0"><tbody>' \
                           '    <!-- ENCABEZADO -->' \
                           '    <tr>' \
                           ' <td style="min-width:590px;" align="center">' \
                           '<table style="min-width:590px;background-color: white; padding: 0px 8px 0px 8px; border-collapse:separate;" width="590" cellspacing="0" cellpadding="0" border="0">' \
                           '<tbody><tr><td valign="middle">' \
                           '<div align="center"><span style="font-size:10px;">Bienvenido/a a SICPRO</span><br></div><span style="font-size:20px;font-weight: bold;">' + data.name + '</span></td><td style="text-align:right;" valign="middle">' \
                                                                                                                                                                                          '<img src="' + url + '/sicpro_app_administracion/static/src/img/logo_sicpro 4.png" style="padding: 0px; margin: 0px; height: auto; width: 25%;">' \
                                                                                                                                                                                                               '</td></tr>' \
                                                                                                                                                                                                               '<tr><td colspan="2" style="text-align:center;">' \
                                                                                                                                                                                                               '<hr style="background-color:rgb(204,204,204);border:medium none;clear:both;display:block;font-size:0px;min-height:1px;line-height:0; margin: 16px 0px 16px 0px;" width="100%">' \
                                                                                                                                                                                                               '</td></tr></tbody></table></td></tr>' \
                                                                                                                                                                                                               '<!-- CONTENIDO --><tr><td style="min-width:590px;" align="center"><table style="min-width:590px;background-color: white; padding: 0px 8px 0px 8px; border-collapse:separate;" ' \
                                                                                                                                                                                                               'width="590" cellspacing="0" cellpadding="0" border="0"><tbody><tr><td style="font-size:13px;" valign="top"><div>Estimado/a ' + data.name + ',<br>' \
                                                                                                                                                                                                                                                                                                                                                                 '<br> Se ha detectado un nuevo inicio de sesión en la aplicación SICPRO ERP. <div style="margin:16px 0px 16px 0px;"><a href="' + url + '" ' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'style="color:rgb(124, 123, 173);background-color:#875A7B;padding: 8px 16px 8px 16px; text-decoration: none; color: #fff; border-radius: 5px; font-size:13px;">Verificar </a>' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '</div><br> <b><i>Los datos del usuario que ha accedido al sistema son:</i></b><br><br><br></div><table class="table table-bordered"><tbody><tr>' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '<td align="center" style="border-style: solid; border-width: 1px"><b><font style="font-size:14px;">USUARIO</font></b></td><td align="center" ' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        'style="border-style: solid; border-width: 1px"><font style="font-size:14px;"><b>IP </b></font></td><td align="center" style="border-style: solid; border-width: 1px"><font style="font-size:14px;">' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '<b>WEB</b></font></td><td align="center" style="border-style: solid; border-width: 1px"><font style="font-size:14px;"><b>SO</b></font></td>' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '<td align="center" style="border-style: solid; border-width: 1px"><font style="font-size:14px;"><b>Fecha</b></font></td></tr><tr>' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '<td align="center" style="border-style: solid; border-width: 1px"><font style="font-size:14px;">' + self.name + '</font></td>' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         '<td align="center" style="border-style: solid; border-width: 1px"><font style="font-size:14px;"><b>&nbsp;</b>' + ip_address + '</font></td>' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        '<td align="center" style="border-style: solid; border-width: 1px"><font style="font-size:14px;"><b>&nbsp;</b>' + navegador_web + '</font></td>' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          '<td align="center" style="border-style: solid; border-width: 1px"><font style="font-size:14px;">' + sistema_operativo + '</font></td>' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   '<td align="center" style="border-style: solid; border-width: 1px">' + fecha + '<br></td></tr></tbody></table><div><br><br>' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '<br> Este correo le llega a usted porque forma parte del grupo de recepción de las alertas del login, puede verificar este acceso desde el módulo de registros de usuarios en la aplicación de Administración. <br>&nbsp;' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '<br><br> ¡Disfrute de SICPRO!<br> --<br>El equipo de administración de SICPRO ERP </div></td></tr><tr><td style="text-align:center;">' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '<hr style="background-color:rgb(204,204,204);border:medium none;clear:both;display:block;font-size:0px;min-height:1px;line-height:0; margin: 16px 0px 16px 0px;" width="100%"></td></tr></tbody></table></td></tr>' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '     <!-- PIE --><tr><td style="min-width:590px;" align="center"><table style="min-width:590px;background-color: white; font-size: 11px; padding: 0px 8px 0px 8px; border-collapse:separate;" width="590" cellspacing="0" cellpadding="0" border="0">' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '<tbody><tr><td style="text-align:left;" valign="middle">' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  'División de Proyecto y Ejecución de Obras</td></tr><tr><td style="opacity:0.7;text-align: left;" valign="middle">+53 52183663' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ' | <a href="mailto:daniel.borrero@etecsa.cu" style="color:#454748;">daniel.borrero@etecsa.cu</a>' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '</td></tr></tbody></table></td></tr></tbody></table></td></tr>' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '<!-- POWERED BY --><tr><td style="min-width:590px;" align="center"><br><table style="min-width:590px;background-color: #F1F1F1; color: #454748; padding: 8px; border-collapse:separate;" width="590" cellspacing="0" cellpadding="0" border="0">' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '<tbody><tr><td style="text-align:center;font-size: 13px;">Recibes notificaciones con la tecnología de <b><a target="_blank" style="color:#875A7B;"><font style="color:rgb(7, 140, 7);">SICPRO' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '</font></a><font style="color:rgb(7, 140, 7);"> <br></font></b></td></tr><tr><td style="text-align:center;font-size: 13px;"><p><font style="font-size: 10px;" class="text-600">© 2021 División de Proyectos y Ejecución, DVPE.</font><br>' \
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  '<font style="font-size: 10px;" class="text-600">Edificio Masónico, Ave. Carlos III / Calle Santiago y Belascoain.</font></p></td></tr></tbody></table></td></tr></tbody></table>'



            template_data = {
                'subject': '•SICPRO ERP: Acceso registrado ' + fecha,
                'body_html': message_body,
                'email_from': request.env.user.company_id.email,
                'email_to': data.email,
                'auto_delete': True}
            template_obj.create(template_data).send()
        # Termina Configuración de Correo
        return result


class LoginUpdate(models.Model):
    _name = 'sicpro.modulo.registro.usuarios'
    _description = 'Registro de usuarios'
    _order = "date_time desc"

    name = fields.Char(string="Nombre de usuario")
    date_time = fields.Datetime(string="Fecha y hora de inicio de sesión",
                                default=lambda self: fields.datetime.now())
    ip_address = fields.Char(string='Dirección IP')
    navegador_web = fields.Char(string='Navegador')
    sistema_operativo = fields.Char(string='Sistema Operativo')
    vpn = fields.Boolean(string='VPN', compute='compute_es_vpn', store=False)

    # identifica las conexiones con vpn
    @api.depends("ip_address")
    def compute_es_vpn(self):
        for item in self:
            ip = item.ip_address[:3]
            if ip == '172':
                item.vpn = True
            else:
                item.vpn = False
