# -*- encoding: utf-8 -*-

{
    'name': 'SICPRO: Web Página Inicial',
    'version': '19.0.0.0.1',
    'category': 'Website',
    'summary': 'Muestra la pagina informativa inicial para SICPRO ERP',
    'description': 'Muestra la pagina informativa inicial para SICPRO ERP',
    'author': 'Daniel Barrero Reyes',
    'maintainer': 'Daniel Barrero Reyes / Soporte Técnico SICPRO',
    'support': 'daniel.borrero@etecsa.cu',
    'price': 0,
    'currency': 'CUP',
    'company': 'División de Proyectos y Ejecución de Obras',
    'website': 'https://www.facebook.com/dannyroses.oficial/',
    'license': 'AGPL-3',
    'sequence': 3,
    "depends": [
        "base",
        'base_setup',
        'web',
        'sicpro_modulo_nomencladores_iconos',
        "sicpro_app_administracion",
        'sicpro_app_trabajadores',
        'sicpro_app_solicitudes',
        'sicpro_app_ordenes_trabajo',
        'sicpro_app_transferencias_gastos',
        ],
    "data": [
        'security/ir.model.access.csv',
        'templates/inicio_template.xml',
        'data/sicpro_modulo_web_aviso_mantenimiento.xml',
        'views/galerias_views.xml',
        'views/equipo_views.xml',
        'views/version_views.xml',
        'views/evolucion_views.xml',
        'views/manuales_views.xml',
        'views/preguntas_views.xml',
        'views/trabajadores_views.xml',
        'views/aviso_mantenimiento_views.xml',
        'views/modulo_web_menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [],
    },
    "installable": True,
    'application': True,
    "auto_install": False,
    "pre_init_hook": "pre_init_check",
}