# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Cuadro de Mando Integral',
    'version': '1.0.0',
    # Estados (Desarrollo o Producción) Desarrollo: Store o actualiza Producción: Store avisa de nueva actualización
    'estado': 'Desarrollo',
    'category': 'Productividad',
    'summary': "La aplicación se encarga de la gestión del CMI de la DVPE.",
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'price': 0,
    'currency': 'CUP',
    'company': 'División de Proyectos y Ejecución de Obras',
    'website': 'https://www.facebook.com/dannyroses.oficial/',
    'license': 'AGPL-3',
    'sequence': 2,
    # 'external_dependencies': {'python': ['nombre del paquete', 'nombre del paquete']},
    'depends': [
        'nucleo_sicpro_erp',
        'base',
        'mail',
        'sicpro_app_administracion',
        'sicpro_modulo_nomencladores',
        'sicpro_modulo_dashboard_extendido',
    ],
    'data': [
        'security/cmi_security.xml',
        'security/ir.model.access.csv',
        'views/cmi_acciones_estados_views.xml',
        'views/cmi_acciones_modo_control_views.xml',
        'views/cmi_indicadores_cambios_views.xml',
        'views/cmi_indicadores_acciones_views.xml',
        'views/cmi_indicadores_views.xml',
        'views/cmi_objetivos_anuales_views.xml',
        'views/cmi_objetivos_estrategicos_views.xml',
        'views/cmi_perspectivas_views.xml',
        'views/cmi_perspectivas_eje_estrategico_views.xml',
        'views/cmi_perspectivas_periodo_views.xml',
        'views/cmi_perspectivas_anios_views.xml',
        'report/indicadores_report_views.xml',
        'data/plantillas_correo_data.xml',
        'data/acciones_estados_data.xml',
        'data/cron_automatizacion.xml',
        'data/periodos_data.xml',
        'informes/cmi_reporte_wizard.xml',
        'informes/cmi_reporte_template_completo.xml',
        'informes/cmi_reporte_template_ejes.xml',
        'informes/cmi_reporte_template_acciones.xml',
        'views/cmi_menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sicpro_app_cmi/static/src/scss/dashboard.scss',
        ],
        'web.assets_qweb': [],
               },
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_check',
    # 'post_init_hook': 'post_init_hook',
    # 'uninstall_hook': 'uninstall_hook',
}
