# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Credenciales',
    'version': '1.0',
    'category': 'Trabajadores',
    'sequence': 2,
    'summary': "Esta aplicación se encargará del control de las credenciales "
               "de accesos de los trabajadores a la entidad",
    'author': 'Daniel Barrero Reyes', 'support': 'daniel.borrero@etecsa.cu',
    'website': 'https://www.facebook.com/danielbarreroreyes.oficial/',
    'license': 'AGPL-3',
    'depends': [
        'nucleo_sicpro_erp',
        'sicpro_app_trabajadores',
        'base',
        'mail',
        'smile_log',
    ],
    'data': ['security/credenciales.xml',
             'security/ir.model.access.csv',
             'informes/credencial_personal.xml',
             'informes/credencial_laptop.xml',
             'views/credenciales_tipo_views.xml',
             'views/credenciales_accesos_views.xml',
             'views/credenciales_siglas_views.xml',
             'views/credenciales_alcance.xml',
             'views/credenciales_views.xml',
             'data/tipos_credencial_data.xml',
             'data/siglas_credencial_data.xml',
             'data/accesos_credencial_data.xml',
             'data/alcance_credencial_data.xml',
             'data/cron_automatizacion.xml',
             'data/plantillas_correo_data.xml',
             'views/credenciales_menu_views.xml',
             ],
    'installable': True,
    'application': True,
    'auto_install': False, }
