# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Credenciales',
    'version': '1.0.0',
    # Estados (Desarrollo o Producción) Desarrollo: Store o actualiza Producción: Store avisa de nueva actualización
    'estado': 'Desarrollo',
    'category': 'Trabajadores',
    'sequence': 2,
    'summary': "Esta aplicación se encargará del control de las credenciales "
               "de accesos de los trabajadores a la entidad",
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'price': 0,
    'currency': 'CUP',
    'company': 'División de Proyectos y Ejecución de Obras',
    'website': 'https://www.facebook.com/dannyroses.oficial/',
    'license': 'AGPL-3',
    # 'external_dependencies': {'python': ['nombre del paquete', 'nombre del paquete']},
    'depends': [
        'nucleo_sicpro_erp',
        'sicpro_app_trabajadores',
        'sicpro_modulo_dashboard_extendido',
        'base',
        'mail',
        'web',
        'web_editor',
    ],
    'data': ['security/credenciales.xml',
             'security/ir.model.access.csv',
             'informes/credencial_personal.xml',
             'informes/credencial_pvc.xml',
             'informes/credencial_laptop.xml',
             'informes/credencial_personal_laptop.xml',
             'views/credenciales_tipo_views.xml',
             'views/credenciales_accesos_views.xml',
             'views/credenciales_siglas_views.xml',
             'views/credenciales_alcance.xml',
             'views/credenciales_cancelacion_views.xml',
             'views/credenciales_views.xml',
             'data/tipos_credencial_data.xml',
             'data/siglas_credencial_data.xml',
             'data/accesos_credencial_data.xml',
             'data/alcance_credencial_data.xml',
             'data/cron_automatizacion.xml',
             'data/plantillas_correo_data.xml',
             'views/credenciales_menu_views.xml',
             'wizards/recortador_de_imagenes.xml',
             ],
    'assets': {
        'web.assets_backend': [
            ('prepend','sicpro_app_credenciales/static/lib/cropperjs/cropper.css'),
            'sicpro_app_credenciales/static/lib/cropperjs/cropper.js',
            'sicpro_app_credenciales/static/lib/jquery-cropper/jquery-cropper.js',
            'sicpro_app_credenciales/static/src/js/image_processing.js',
            'sicpro_app_credenciales/static/src/js/image_crop_widget.js',
            'sicpro_app_credenciales/static/src/js/imagen_con_recortar.js',
            ('after','web/static/src/legacy/scss/fields.scss','sicpro_app_credenciales/static/src/scss/imagen_con_recortar.scss'),
            'sicpro_app_credenciales/static/src/js/recortando_imagen.js',
            'sicpro_app_credenciales/static/src/scss/recortador.scss',
        ], 
        'web.assets_qweb': [
            'sicpro_app_credenciales/static/src/**/*.xml',
            ('remove', 'sicpro_app_credenciales/static/src/**/*.xml'),
            ('after', 'web/static/src/legacy/xml/base.xml', 'sicpro_app_credenciales/static/src/xml/templates_recortador.xml'),
            'sicpro_app_credenciales/static/src/xml/templates_recortador_original.xml',
        ],
        'web.report_assets_common':[
            'sicpro_app_credenciales/static/src/css/credencial_pvc.css',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_check',
    # 'post_init_hook': 'post_init_hook',
    # 'uninstall_hook': 'uninstall_hook',
}
