# -*- coding: utf-8 -*-

from . import sicpro_app_trabajadores
from . import sicpro_app_trabajadores_categorias
from . import sicpro_app_trabajadores_areas
from . import sicpro_app_trabajadores_ocupacion
from . import sicpro_app_trabajadores_locales
from . import sicpro_app_trabajadores_familiar
from . import sicpro_app_trabajadores_nexo_familiar
from . import ir_attachment
from . import sicpro_app_trabajadores_documentos
from . import sicpro_app_trabajadores_documentos_plantillas
from . import sicpro_app_trabajadores_documentos_tipos
from . import sicpro_app_trabajadores_disciplinarias_accion
from . import sicpro_app_trabajadores_disciplinarias_categoria
from . import sicpro_app_trabajadores_cursos
from . import sicpro_app_trabajadores_cursos_habilidades
from . import sicpro_app_trabajadores_cursos_niveles
from . import sicpro_app_trabajadores_cursos_tipos
from . import sicpro_app_trabajadores_educacion
from . import sicpro_app_trabajadores_educacion_tipos
from . import sicpro_app_trabajadores_educacion_certificacion
from . import sicpro_app_trabajadores_organigrama
from . import sicpro_app_trabajadores_equipo_tecnico
from . import sicpro_app_trabajadores_claves_horas
from . import sicpro_app_trabajadores_cargos
from . import res_users
from . import sicpro_app_trabajadores_vacunación
from . import sicpro_app_trabajadores_intrucciones
from . import sicpro_app_trabajadores_seguridad_proteccion
from . import sicpro_app_trabajadores_proteccion_trabajador
from . import sicpro_app_trabajadores_tallas
