# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Transporte',
    'version': '1.0.0',
    # Estados (Desarrollo o Producción) Desarrollo: Store o actualiza Producción: Store avisa de nueva actualización
    'estado': 'Desarrollo',
    'sequence': 2,
    'category': 'Human Resources/Productivity',
    'summary': "Esta aplicación se encargará de todo el control del parqué "
               "automotor de la división.",
    # 'external_dependencies': {'python': ['nombre del paquete', 'nombre del paquete']},
    'depends': [
        'nucleo_sicpro_erp',
        'base',
        'mail',
        'sicpro_modulo_nomencladores',
        'sicpro_app_trabajadores',
        'sicpro_modulo_widget_contador',
        'sicpro_modulo_dashboard_extendido',
    ],
    'website': 'https://www.facebook.com/dannyroses.oficial/',
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'price': 0,
    'currency': 'CUP',
    'license': 'AGPL-3',
    'data': [
        'security/transporte.xml',
        'security/ir.model.access.csv',
        'informes/informe_modelo_m1.xml',
        'informes/informe_costo_piquera.xml',
        'views/transporte_modelo_views.xml',
        'views/transporte_views.xml',
        'views/transporte_distancias_views.xml',
        'views/transporte_combustible_views.xml',
        'views/transporte_estado_views.xml',
        'views/transporte_trabajadores.xml',
        'views/transporte_piquera_view.xml',
        'data/Transporte_fabricantes_data.xml',
        'data/estados_data.xml',
        'data/plantillas_correo_data.xml',
        'views/transporte_menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [],
        'web.assets_qweb': [],
        'web.report_assets_common': [
            'sicpro_app_transporte/static/src/css/informe_modelo_m1.scss',
            'sicpro_app_transporte/static/src/css/informe_costo_piquera.scss',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_check',
    # 'post_init_hook': 'post_init_hook',
    # 'uninstall_hook': 'uninstall_hook',,
}
