# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Contratos',
    'version': '1.0',
    'sequence': 2,
 'category': 'Contabilidad', 'summary': "Contratos",
 'website': 'https://www.facebook.com/danielbarreroreyes.oficial/',
 'author': 'Daniel Barrero Reyes', 'support': 'daniel.borrero@etecsa.cu',
 'license': 'AGPL-3',
 'description': "Esta aplicación se encargará de todo el control de los "
                "contratos y proveedores de la división, así como del "
                "proceso de contabilidad.",
 'depends': ['nucleo_sicpro_erp',
             'base', 'web',
             'base_setup',
             'sicpro_app_administracion',
             'sicpro_modulo_nomencladores',
             'smile_log',
             ],
 'data': ['security/contratos.xml',
          'security/ir.model.access.csv',
          'views/contratos.xml',
          'views/contratos_proveedores_etiquetas_views.xml',
          'views/contratos_proveedores_tipo_views.xml',
          'views/contratos_proveedores_estados_views.xml',
          'views/contratos_tipo_views.xml',
          'views/contratos_estados_views.xml',
          'views/contratos_dias_views.xml',
          'views/contratos_etiquetas_views.xml',
          'views/contratos_unidades_views.xml',
          'views/contratos_areas_views.xml',
          'views/contratos_proveedores.xml',
          'views/contratos_economia.xml',
          'views/contratos_beneficiarios_views.xml',
          'views/contratos_economia_estados_views.xml',
          'views/contratos_economia_etiquetas_views.xml',
          'views/contratos_economia_pago_views.xml',
          'views/contratos_economia_indicador_views.xml',
          'views/contratos_economia_acapite_views.xml',
          'views/contratos_economia_bancos_views.xml',
          'views/contratos_economia_cuentas_dvpe_views.xml',
          'data/economia_tipo_pago_data.xml',
          'data/proveedores_estados.xml',
          'data/proveedores_tipo.xml',
          'data/contratos_unidades.xml',
          'data/contratos_areas.xml',
          'data/contratos_estados.xml',
          'data/contratos_tipo.xml',
          'data/contratos_dias_habiles.xml',
          'data/economia_estados.xml',
          'data/economia_cuentas_dvpe_data.xml',
          'data/contratos_beneficiarios_data.xml',
          'data/economia_banco_data.xml',
          'data/plantillas_correo_data.xml',
          'informes/informe_solicitud_pago_views.xml',
          'informes/informe_solicitud_instrumento_pago_views.xml',
          'informes/informe_poliza_pago_views.xml',
          'informes/transferencia_bancaria_metropolitano_views.xml',
          'informes/transferencia_bancaria_bfi_views.xml',
          'informes/informe_cancelacion_cheque_views.xml',
          'informes/informe_aval_economico_views.xml',
          'informes/informe_evaluacion_proveedor_views.xml',
          'report/proveedores_report_views.xml',
          'report/contratos_report_views.xml',
          'report/economia_report_views.xml',
          'dashboard/board_templates.xml',
          'dashboard/board_views.xml',
          'views/contratos_menu_views.xml', ],

 'qweb': ['static/src/xml/dashboard_contratos.xml'],
 'installable': True,
 'application': True,
 'auto_install': False,

 }
