# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Contratos',
    'version': '1.0.0',
    # Estados (Desarrollo o Producción) Desarrollo: Store o actualiza Producción: Store avisa de nueva actualización
    'estado': 'Desarrollo',
    'sequence': 2,
    'category': 'Contabilidad',
    'summary': "Contratos",
    'website': 'https://www.facebook.com/dannyroses.oficial/',
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'price': 0,
    'currency': 'CUP',
    'company': 'División de Proyectos y Ejecución de Obras',
    'license': 'AGPL-3',
    'description': "Esta aplicación se encargará de todo el control de los "
                "contratos y proveedores de la división, así como del "
                "proceso de contabilidad.",
    # 'external_dependencies': {'python': ['nombre del paquete', 'nombre del paquete']},
    'depends': [
        'nucleo_sicpro_erp',
        'base',
        'sicpro_app_administracion',
        'sicpro_modulo_nomencladores',
        'sicpro_modulo_dashboard_extendido',
    ],
    'data': [
        'security/contratos.xml',
        'security/ir.model.access.csv',
        'views/contratos.xml',
        'views/contratos_proveedores_etiquetas_views.xml',
        'views/contratos_proveedores_tipo_views.xml',
        'views/contratos_proveedores_estados_views.xml',
        'views/contratos_tipo_views.xml',
        'views/contratos_estados_views.xml',
        'views/contratos_dias_views.xml',
        'views/contratos_etiquetas_views.xml',
        'views/contratos_unidades_views.xml',
        'views/contratos_areas_views.xml',
        'views/contratos_proveedores.xml',
        'views/contratos_economia.xml',
        'views/contratos_beneficiarios_views.xml',
        'views/contratos_economia_estados_views.xml',
        'views/contratos_economia_etiquetas_views.xml',
        'views/contratos_economia_pago_views.xml',
        'views/contratos_economia_indicador_views.xml',
        'views/contratos_economia_acapite_views.xml',
        'views/contratos_economia_bancos_views.xml',
        'views/contratos_economia_cuentas_dvpe_views.xml',
        'data/economia_tipo_pago_data.xml',
        'data/proveedores_estados.xml',
        'data/proveedores_tipo.xml',
        'data/contratos_unidades.xml',
        'data/contratos_areas.xml',
        'data/contratos_estados.xml',
        'data/contratos_tipo.xml',
        'data/contratos_dias_habiles.xml',
        'data/economia_estados.xml',
        'data/economia_cuentas_dvpe_data.xml',
        'data/contratos_beneficiarios_data.xml',
        # se deshabilitó por cambios en nomencladores de provincia y municipio
        # 'data/economia_banco_data.xml',
        'data/plantillas_correo_data.xml',
        'informes/informe_solicitud_pago_views.xml',
        'informes/informe_solicitud_instrumento_pago_views.xml',
        'informes/informe_poliza_pago_views.xml',
        'informes/transferencia_bancaria_metropolitano_views.xml',
        'informes/transferencia_bancaria_bfi_views.xml',
        'informes/informe_cancelacion_cheque_views.xml',
        'informes/informe_aval_economico_views.xml',
        'informes/informe_evaluacion_proveedor_views.xml',
        'informes/informe_sap_proveedor_anexo2_views.xml',
        'informes/informe_sap_proveedor_nacionales_views.xml',
        'informes/informe_sap_proveedor_tcp_views.xml',
        'report/proveedores_report_views.xml',
        'report/contratos_report_views.xml',
        'report/economia_report_views.xml',
        'views/contratos_menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [],
        'web.assets_qweb': [],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_check',
    # 'post_init_hook': 'post_init_hook',
    # 'uninstall_hook': 'uninstall_hook',

 }
