# -*- encoding: utf-8 -*-

{
    'name': 'SICPRO: Web Página Versiones',
    'version': '1.0.0',
    # Estados (Desarrollo o Producción) Desarrollo: Store o actualiza Producción: Store avisa de nueva actualización
    'estado': 'Desarrollo',
    'category': 'Administración',
    'summary': 'Muestra la página informativa con los cambios en las versiones realizadas para SICPRO ERP',
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'price': 0,
    'currency': 'CUP',
    'company': 'División de Proyectos y Ejecución de Obras',
    'website': 'https://www.facebook.com/dannyroses.oficial/',
    'license': 'AGPL-3',
    'sequence': 3,
    "depends": ['nucleo_sicpro_erp',
                "sicpro_app_administracion",
                "base",
                'sicpro_modulo_dominio_dinamico',
                'sicpro_modulo_web',
                'sicpro_modulo_web_login',
                'sicpro_app_soporte',
                ],
    "data": [
        'security/ir.model.access.csv',
        'templates/versiones_template.xml',
        'templates/login_template.xml',
        'templates/web_template.xml',
        'views/version_view.xml',
        'views/versiones_views.xml',
        'views/versiones_menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [],
        'web.web_versiones': [
            'sicpro_modulo_web_versiones/static/src/vendor/aos/aos.css',
            'sicpro_modulo_web_versiones/static/src/vendor/bootstrap/css/bootstrap.min.css',
            'sicpro_modulo_web_versiones/static/src/vendor/bootstrap-icons/bootstrap-icons.css',
            'sicpro_modulo_web_versiones/static/src/vendor/boxicons/css/boxicons.min.css',
            'sicpro_modulo_web_versiones/static/src/vendor/glightbox/css/glightbox.min.css',
            'sicpro_modulo_web_versiones/static/src/vendor/swiper/swiper-bundle.min.css',
            'sicpro_modulo_web_versiones/static/src/css/style.css',
        ],
        'web.web_versiones_js': [
            'sicpro_modulo_web_versiones/static/src/vendor/aos/aos.js',
            'sicpro_modulo_web_versiones/static/src/vendor/glightbox/js/glightbox.min.js',
            'sicpro_modulo_web_versiones/static/src/vendor/swiper/swiper-bundle.min.js',
            'sicpro_modulo_web_versiones/static/src/vendor/typed.js/typed.min.js',
            'sicpro_modulo_web_versiones/static/src/vendor/waypoints/noframework.waypoints.js',
            'sicpro_modulo_web_versiones/static/src/js/main.js',
        ],
    },
    "installable": True,
    'application': True,
    "auto_install": False,
    "pre_init_hook": "pre_init_check",
}