# -*- coding: utf-8 -*-
{
    'name': 'SICPRO: Administración',
    'version': '1.0',
    'summary': "Aplicación para la administración de SICPRO ERP",
    'description': "Aplicación para la administración de SICPRO ERP",
    'category': 'Administración',
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'website': "https://www.facebook.com/danielbarreroreyes.oficial/",
    'license': 'AGPL-3',
    'sequence': 1,
    'depends': [
        'base',
        'mail',
        'web',
        'smile_log',
        'base_automation',
        'nucleo_sicpro_erp',
        'sicpro_modulo_roles',
        'sicpro_modulo_importar_seguridad',
    ],

    'data': [
        'security/administracion.xml',
        'security/ir.model.access.csv',
        'views/ir_attachment_views.xml',
        'views/res_users_view.xml',
        'views/nube_aplicaciones_views.xml',
        'views/ir_module_view.xml',
        'views/res_company.xml',
        'views/cambios_versiones_js.xml',
        'views/cambios_versiones_views.xml',
        'views/cambios_versiones_modal_views.xml',
        'views/eliminar_burbuja.xml',
        'views/arrastrar_adjuntos_views.xml',
        'views/expandir_vista_grupos_views.xml',
        'views/web_debug.xml',
        'data/versiones_cambios_data.xml',
        'data/res_company_data.xml',
        'data/mail_channel_data.xml',
        'data/res_user_data.xml',
        'data/ir_mail_server_data.xml',
        'data/mail_template_data.xml',
        'data/ir_cron_data.xml',
        'data/mantenimiento_data.xml',
        'data/ir_config_parameter.xml',
        # 'data/resource_data.xml',
        'views/barra_conversacion_canales.xml',
        'views/administracion_mantenimiento_views.xml',
        'views/sicpro_app_administracion.xml',
        'wizard/image_importer_wizard_views.xml',
        'views/administracion_menu_views.xml',
    ],
    'qweb': ['static/src/xml/cambios_versiones_modal.xml',
             'static/src/xml/web_boton_debug.xml',
             "static/src/xml/widgets.xml",
             "static/src/xml/expand_buttons.xml",
             # 'static/src/xml/base_import.xml'
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
