# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Dashboard Extendidos',
    'version': '1.0.0',
    # Estados (Desarrollo o Producción) Desarrollo: Store o actualiza Producción: Store avisa de nueva actualización
    'estado': 'Desarrollo',
    'summary': "Módulo para extender a las aplicaciones una vista de dashboard dinámico",
    'description': "Módulo para extender a las aplicaciones una vista de dashboard dinámico",
    'category': 'Administración',
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'price': 0,
    'currency': 'CUP',
    'company': 'División de Proyectos y Ejecución de Obras',
    'website': "https://www.facebook.com/dannyroses.oficial/",
    'license': 'AGPL-3',
    'sequence': 1,
    # 'external_dependencies': {'python': ['nombre del paquete', 'nombre del paquete']},
    'depends': [
        'base',
        'nucleo_sicpro_erp',
        'sicpro_app_administracion',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/dashboard_tableros_views.xml',
        'views/dashboard_secciones_views.xml',
        'views/dashboard_grupos_views.xml',
        'views/dashboard_graficos_views.xml',
        'views/dashboard_iconos_views.xml',
        'views/dashboard_colores_views.xml',
        'data/dashboard_iconos_data.xml',
        'views/dashboard_menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sicpro_modulo_dashboard_extendido/static/src/css/dashboard.css',
            'sicpro_modulo_dashboard_extendido/static/src/css/style.scss',
            'sicpro_modulo_dashboard_extendido/static/src/css/material-gauge.css',
            'sicpro_modulo_dashboard_extendido/static/src/js/dashboard_view.js',
            'sicpro_modulo_dashboard_extendido/static/src/lib/highcharts.js',
            'sicpro_modulo_dashboard_extendido/static/src/lib/Chart.bundle.js',
            'sicpro_modulo_dashboard_extendido/static/src/lib/chartjs-plugin-datalabels.min.js',
            'sicpro_modulo_dashboard_extendido/static/src/lib/funnel.js',
            'sicpro_modulo_dashboard_extendido/static/src/lib/d3.min.js',
            'sicpro_modulo_dashboard_extendido/static/src/lib/material-gauge.js',
            'sicpro_modulo_dashboard_extendido/static/src/lib/columnHeatmap.min.js',
            'sicpro_modulo_dashboard_extendido/static/src/lib/columnHeatmap.js',
            'sicpro_modulo_dashboard_extendido/static/src/js/dashboard_icon_char.js',
            'sicpro_modulo_dashboard_extendido/static/src/lib/html2pdf.bundle.js',
        ],
        'web.assets_frontend': [],
        'web.assets_qweb': [
            'sicpro_modulo_dashboard_extendido/static/src/xml/dashboard_view.xml',
            'sicpro_modulo_dashboard_extendido/static/src/xml/dashboard_icon_template.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_check',
    # 'post_init_hook': 'post_init_hook',
    # 'uninstall_hook': 'uninstall_hook',
}
