# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Control de la Información',
    'version': '1.0.0',
    # Estados (Desarrollo o Producción) Desarrollo: Store o actualiza Producción: Store avisa de nueva actualización
    'estado': 'Desarrollo',
    'sequence': 2,
    'category': 'Producción',
    'summary': "Esta aplicación se encarga del control y gestión de las informaciones que se procesan en la DVPE.",
    'website': 'https://www.facebook.com/dannyroses.oficial/',
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'price': 0,
    'currency': 'CUP',
    'company': 'División de Proyectos y Ejecución de Obras',
    'license': 'AGPL-3',
    # 'external_dependencies': {'python': ['nombre del paquete', 'nombre del paquete']},
    'depends': [
        'nucleo_sicpro_erp',
        'base',
        'calendar',
        'sicpro_app_trabajadores',
        'sicpro_modulo_dashboard_extendido',
    ],
    'data': [
        'security/informaciones.xml',
        'security/ir.model.access.csv',
        'data/plantillas_correo_data.xml',
        'data/cron_automatizacion.xml',
        'views/control_informacion_areas_views.xml',
        'views/control_informacion_actividades_views.xml',
        'views/control_informacion_actividades_control_view.xml',
        'views/control_informacion_dashboard_view.xml',
        'views/control_informacion_etiquetas_views.xml',
        'views/control_informacion_dias_views.xml',
        'views/control_informacion_motivo_devolucion_views.xml',
        'views/control_informacion_views.xml',
        'informes/dinamica_atividades_evaluacion_view.xml',
        'views/control_informacion_menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [],
        'web.assets_qweb': [],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_check',
    # 'post_init_hook': 'post_init_hook',
    # 'uninstall_hook': 'uninstall_hook',
}
