[options]
; Configuración de SICPRO ERP: DESARROLLO
;###################################################################################################
;###################################################################################################
admin_passwd = Rosario.25.
db_host = 127.0.0.1
db_port = 5432
db_user = odoo
db_password = Jesus*25*
;###################################################################################################
;###################################################################################################
;db_name = sicpro
db_maxconn = 64
db_sslmode = prefer
;###################################################################################################
;###################################################################################################
data_dir = /home/daniel.borrero/SICPRO ERP/MESA DE LUZ/Odoo14/sicpro_erp/Produccion/data
logfile = /home/daniel.borrero/SICPRO ERP/MESA DE LUZ/Odoo14/sicpro_erp/Produccion/log/sicpro_server.log
;log_level = warn
logrotate = True
addons_path = /home/daniel.borrero/SICPRO ERP/MESA DE LUZ/Odoo14/sicpro_erp/odoo/addons,
              /home/daniel.borrero/SICPRO ERP/MESA DE LUZ/Odoo14/sicpro_erp/Produccion/apps
;###################################################################################################
;###################################################################################################
longpolling_port = 8072
xmlrpc = True
xmlrpc_port = 8069
netrpc_interface = 127.0.0.1
xmlrpc_interface = 127.0.0.1
;###################################################################################################
;###################################################################################################
workers = 0
limit_time_cpu = 120
limit_time_real = 240
max_cron_threads = 2
;###################################################################################################
;###################################################################################################
proxy_mode = True
;###################################################################################################
;###################################################################################################
;[Base_rest]
;dev_mode = True
;dbfilter = ^prueba$
;###################################################################################################
;###################################################################################################