[options]

; Configuración de SICPRO ERP (Desarrollo en Odoo 19)
; --------------------------------------------------------------------------------

; SEGURIDAD
admin_passwd = Rosario.35.
proxy_mode = True

; BASE DE DATOS
db_host = 127.0.0.1
db_port = 5432
db_user = odoo
db_password = Rosario.35.
;db_name = sicpro
;dbfilter = ^sicpro$
db_maxconn = 64
db_sslmode = prefer

; RUTAS Y LOGGING
data_dir = /home/dany/odoo/sicproerp/data
; comentado el logfile para el desarrollo , para que aparezca el log en el terminal de pycharm
;logfile =  /home/dany/odoo/sicproerp/log/sicpro_server.log
;log_level = warn
addons_path = /home/dany/odoo/sicproerp/odoo/addons,/home/dany/odoo/sicproerp/sicpro_app

; CONECTIVIDAD
gevent_port = 8072
http_port = 8069
http_interface = 127.0.0.1

; =======================================================
; OPTIMIZACIÓN DE RENDIMIENTO (4GB RAM / 1 vCPU)
; =======================================================

; PROCESOS (Workers)
workers = 2
max_cron_threads = 1

; MEMORIA (En Bytes para mayor precisión en Odoo)
; ~3 GB (Límite máximo antes de terminación forzada)
limit_memory_hard = 3221225472
; ~2.4 GB (Límite suave antes de reinicio de worker)
limit_memory_soft = 2576980378

; TIEMPOS (En segundos)
limit_time_cpu = 600
limit_time_real = 1200
limit_request = 8192
