# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Nomencladores',
    'version': '1.0.0',
    # Estados (Desarrollo o Producción) Desarrollo: Store o actualiza Producción: Store avisa de nueva actualización
    'estado': 'Desarrollo',
    'category': 'Administración',
    'summary': "Este módulo agrega todas las bases de nomencladores que "
               "serán utilizados",
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'price': 0,
    'currency': 'CUP',
    'website': 'https://www.facebook.com/dannyroses.oficial/',
    'license': 'AGPL-3',
    'sequence': 3,
    # 'external_dependencies': {'python': ['nombre del paquete', 'nombre del paquete']},
    'depends': ['nucleo_sicpro_erp',
                'base',
                'resource',
                'sicpro_app_administracion',
                ],
    'data': [
        'security/nomencladores_security.xml',
        'security/ir.model.access.csv',
        'views/trimestres_views.xml',
        'views/meses_views.xml',
        'views/especialidades.views.xml',
        'views/territorios_views.xml',
        'views/cuentas_contables_views.xml',
        'views/res_municipality.xml',
        'views/res_state.xml',
        'views/centro_costo_views.xml',
        'views/locales_cc_views.xml',
        'views/meses_views.xml',
        'views/departamentos_views.xml',
        'views/anios_views.xml',
        'views/centro_planificacion_views.xml',
        'views/emplazamiento_views.xml',
        'views/areas_empresa_views.xml',
        # Data
        'data/res_country_state_data.xml',
        'data/res_municipality_data.xml',
        'data/meses_data.xml',
        'data/territorios_data.xml',
        'data/trimestre_data.xml',
        'data/especialidad_data.xml',
        'data/anios_data.xml',
        'data/centro_planificacion_data.xml',
        'data/emplazamiento_data.xml',
        'data/areas_empresa_data.xml',
        'views/nomencladores_views.xml',

    ],
    'assets': {
        'web.assets_backend': [],
        'web.qunit_suite_tests': [],
        'web.assets_qweb': [],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_check',
    # 'post_init_hook': 'post_init_hook',
    # 'uninstall_hook': 'uninstall_hook',
}
