# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Nomencladores',
    'version': '1.0',
    'category': 'Administración',
    'summary': "Este módulo agrega todas las bases de nomencladores que "
               "seran utilizados",
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'website': 'https://www.facebook.com/danielbarreroreyes.oficial/',
    'license': 'AGPL-3',
    'sequence': 1,
    'depends': ['nucleo_sicpro_erp',
                'base',
                'resource',
                'sicpro_app_administracion',
                ],
    'data': [
        'security/nomencladores_security.xml',
        'security/ir.model.access.csv',
        'views/trimestres_views.xml',
        'views/meses_views.xml',
        'views/especialidades.views.xml',
        'views/territorios_views.xml',
        'views/provincia_views.xml',
        'views/cuentas_contables_views.xml',
        'views/municipio_views.xml',
        'views/problemas_ejecucion_views.xml',
        'views/tipos_ordenes_views.xml',
        'views/centro_costo_views.xml',
        'views/locales_cc_views.xml',
        'views/tarifa_horaria_views.xml',
        'views/variables_estadisticas_views.xml',
        'views/meses_views.xml',
        'views/dieta_views.xml',
        'views/pasaje_views.xml',
        'views/hospedaje_views.xml',
        'views/departamentos_views.xml',
        'views/anios_views.xml',
        # Data
        'data/provincias_data.xml',
        'data/meses_data.xml',
        'data/territorios_data.xml',
        'data/trimestre_data.xml',
        'data/dieta_data.xml',
        'data/especialidad_data.xml',
        'data/tarifa_horaria_data.xml',
        'data/variables_data.xml',
        'data/municipios_data.xml',
        'data/anios_data.xml',
        'views/nomencladores_views.xml',

    ],
    'installable': True,
    'application': True,
}
