# -*- coding: utf-8 -*-
{
    'name': 'SICPRO: Nomencladores',
    'version': '1.0',
    'category': 'Herramientas',
    'summary': "Este módulo agrega todas las bases de nomencladores que "
               "seran utilizados",
    'author': 'Daniel Barrero Reyes',
    'website': 'https://www.facebook.com/daniel.barrero.1253',
    'license': 'AGPL-3',
    'sequence': 1,
    'depends': ['base',
                'sicpro_app_sistema_general',
                'resource',
                ],
    'data': [
        'security/nomencladores_security.xml',
        'security/ir.model.access.csv',
        'views/claves_horas_labor_views.xml',
        'views/trimestres_views.xml',
        'views/meses_views.xml',
        'views/especialidades.views.xml',
        'views/territorios_views.xml',
        'views/provincia_views.xml',
        'views/cuentas_contables_views.xml',
        'views/municipio_views.xml',
        'views/problemas_ejecucion_views.xml',
        'views/tipos_ordenes_views.xml',
        # 'views/mail_activity_views.xml',
        'views/centro_costo_views.xml',
        'views/locales_cc_views.xml',
        'views/tarifa_horaria_views.xml',
        'views/categoria_ocupacional_views.xml',
        'views/variables_estadisticas_views.xml',
        'views/meses_views.xml',
        'views/dieta_views.xml',
        'views/pasaje_views.xml',
        'views/hospedaje_views.xml',
        'views/nomencladores_views.xml',

    ],
    'installable': True,
    'application': True,
}
