from . import sicpro_app_soporte
from . import sicpro_app_soporte_estados
from . import sicpro_app_soporte_etiquetas
from . import sicpro_app_soporte_canales
from . import sicpro_app_soporte_categorias
from . import sicpro_app_soporte_equipos
from . import res_partner
from . import sicpro_app_soporte_estados_versiones
from . import sicpro_app_soporte_estados_aplicaciones
from . import sicpro_app_soporte_estados_paquetes
from . import sicpro_app_soporte_versiones
from . import sicpro_app_soporte_aplicaciones
from . import sicpro_app_soporte_paquetes
from . import sicpro_app_soporte_bitacora
