# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Órdenes de Trabajo',
    'version': '1.0.0',
    # Estados (Desarrollo o Producción) Desarrollo: Store o actualiza Producción: Store avisa de nueva actualización
    'estado': 'Desarrollo',
    'sequence': 2,
    'category': 'Ordenes',
    'summary': "Esta aplicación se encarga de la creación y control de las órdenes de trabajo "
               "de inversiones y mantenimiento.",
    'website': 'https://www.facebook.com/dannyroses.oficial/',
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'price': 0,
    'currency': 'CUP',
    'company': 'División de Proyectos y Ejecución de Obras',
    'license': 'AGPL-3',
    # 'external_dependencies': {'python': ['nombre del paquete', 'nombre del paquete']},
    'depends': [
        'nucleo_sicpro_erp',
        'sicpro_app_administracion',
        'base',
        'calendar',
        'sicpro_app_clientes',
        'sicpro_app_trabajadores',
        'sicpro_app_transporte',
        'sicpro_app_solicitudes',
        'sicpro_modulo_dominio_dinamico',
        'sicpro_modulo_dashboard_extendido',
    ],
    'data': [
        'security/ordenes.xml',
        'security/ir.model.access.csv',
        'data/clase_proyecto_data.xml',
        'data/etiquetas_data.xml',
        'data/problemas_ejecucion_data.xml',
        'data/estados_data.xml',
        'data/nomenclador_consecutivo_data.xml',
        'data/programa_inversiones_data.xml',
        'data/plantillas_correo_data.xml',
        'data/causa_paralizacion_data.xml',
        'views/ordenes_estados_views.xml',
        'views/ordenes_consecutivos_views.xml',
        'views/ordenes_etiquetas_views.xml',
        'views/ordenes_clases_proyectos_views.xml',
        'views/ordenes_paralizacion_views.xml',
        'views/ordenes_problemas_views.xml',
        'views/ordenes_programa_inversiones_views.xml',
        'views/ordenes_trabajo_views.xml',
        'views/ordenes_estado_ordenes_views.xml',
        'informes/informe_ordenes_anexo_3_views.xml',
        'wizard/ordenes_modelo_anexo3_views.xml',
        'views/ordenes_estados_trabajador_views.xml',
        'views/ordenes_estados_transporte_equipos_views.xml',
        'views/ordenes_grupos_transporte_equipos_views.xml',
        'views/ordenes_menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [],
        'web.assets_qweb': [], },
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_check',
    # 'post_init_hook': 'post_init_hook',
    # 'uninstall_hook': 'uninstall_hook',
}
