# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Script installer',
    'version': '1.0',
    'category': 'Herramientas',
    'summary': "Esta herramienta permite la instalación automática de "
               "todas las aplicaciones y modulos SICPRO ERP",
    'author': 'Daniel Barrero Reyes',
    'website': 'https://www.facebook.com/daniel.barrero.1253',
    'license': 'AGPL-3',
    'sequence': 0,
    'depends': [
        'mail',
        'calendar',
        'note',
        'survey',
        'sicpro_app_sistema_general',
        'sicpro_modulo_nomencladores',
        'app_odoo_customize',
        'mass_editing',
        'auditlog',
        'sicpro_modulo_autonumeracion_tree',
        'sicpro_modulo_detalles_usuarios',
        'sicpro_modulo_historial',
        'web_notify',
        'sicpro_app_trabajadores',
        'sicpro_app_clientes',
        'sicpro_app_metrologia',
        'sicpro_app_proyectos',
        'sicpro_app_transporte',
        'app_odoo_customize',
        'sicpro_modulo_temavisual',
        'sicpro_modulo_web_login',
        'smile_log',
        'smile_base_automation',
        #'sicpro_modulo_actividad_reciente',
    ],
    'installable': True,
    'application': True,
}
