# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Víveres',
    'version': '1.0',
    'sequence': 2,
    'category': 'Víveres',
    'summary': "Esta aplicación se encarga del control de la entrega de víveres a los trabajadores.",
    'website': 'https://www.facebook.com/dannyroses.oficial/',
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'price': 0,
    'currency': 'CUP',
    'company': 'División de Proyectos y Ejecución de Obras',
    'license': 'AGPL-3',
    'depends': [
        'nucleo_sicpro_erp',
        'base',
        'sicpro_app_administracion',
        'sicpro_modulo_nomencladores',
        'sicpro_app_trabajadores',
        'sicpro_modulo_dashboard_extendido',
    ],
    'data': [
        'security/viveres.xml',
        'security/ir.model.access.csv',
        'data/plantillas_correo_data.xml',
        'data/productos_data.xml',
        'wizard/viveres_trabajadores_entrega_wizard_views.xml',
        'views/viveres_views.xml',
        'views/viveres_productos_views.xml',
        'views/viveres_productos_comprados_views.xml',
        'views/viveres_cierre_views.xml',
        'views/viveres_areas_entregas_resumenes_views.xml',
        'views/viveres_areas_fondo_views.xml',
        'views/viveres_areas_entregas_views.xml',
        'views/viveres_trabajadores_entregas_views.xml',
        'views/viveres_areas_altas_bajas_views.xml',
        'views/viveres_areas_efectivo_views.xml',
        'views/viveres_areas_views.xml',
        'views/viveres_trabajador_views.xml',
        'views/viveres_menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            '/sicpro_app_viveres/static/src/js/viveres_distribuir_productos.js',
        ],
        'web.assets_qweb': [
            'sicpro_app_viveres/static/src/xml/viveres_distribuir_productos.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    "pre_init_hook": "pre_init_check",
}