# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Instrucciones Laborales',
    'version': '1.0',
    'sequence': 2,
    'category': 'Productividad',
    'summary': "Esta aplicación se encargara de todo el control de las "
               "instrucciones que se le realizan a los trabajadores",
    'website': 'https://www.facebook.com/danielbarreroreyes.oficial/',
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'license': 'AGPL-3',
    'depends': ['nucleo_sicpro_erp',
                'base',
                'mail',
                'sicpro_app_trabajadores',
                'sicpro_app_encuestas',
                ],
    'data': [
        'security/instrucciones.xml',
        'security/ir.model.access.csv',
        'views/instrucciones_templates.xml',
        'views/instrucciones_tipos_views.xml',
        'views/instrucciones_etiquetas_views.xml',
        'views/instrucciones_instruccion_views.xml',
        'views/instrucciones_trabajador_views.xml',
        'views/instrucciones_dashboard_views.xml',
        'data/cron_automatizacion.xml',
        'data/instrucciones_tipo_data.xml',
        'data/plantillas_correo_data.xml',
        'views/instrucciones_menu_views.xml',
    ],
    'installable': True,
    'application': True,
}
