# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Trabajadores',
    'version': '1.0.0',
    # Estados (Desarrollo o Producción) Desarrollo: Store o actualiza Producción: Store avisa de nueva actualización
    'estado': 'Desarrollo',
    'category': 'Trabajadores',
    'sequence': 2,
    'summary': "Esta aplicación se encargará del control de los datos de los trabajadores.",
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'price': 0,
    'currency': 'CUP',
    'company': 'División de Proyectos y Ejecución de Obras',
    'website': 'https://www.facebook.com/dannyroses.oficial/',
    'license': 'AGPL-3',
    # 'external_dependencies': {'python': ['nombre del paquete', 'nombre del paquete']},
    'depends': [
        'nucleo_sicpro_erp',
        'base',
        'mail',
        'resource',
        'calendar',
        'sicpro_app_administracion',
        'sicpro_modulo_nomencladores',
    ],
    'data': [
        'security/trabajadores.xml',
        'security/ir.model.access.csv',
        'views/trabajadores_ocupacion_views.xml',
        'views/trabajadores_categorias_views.xml',
        'views/res_user.xml',
        'views/trabajadores_familiar_views.xml',
        'views/trabajadores_views.xml',
        'views/trabajadores_areas_views.xml',
        'views/trabajadores_tipo_documento_view.xml',
        'views/trabajadores_plantillas_documentos_views.xml',
        'views/trabajadores_documentos_view.xml',
        'views/trabajadores_disciplinaria_categorias_view.xml',
        'views/trabajadores_disciplinarias_acciones.xml',
        'views/trabajadores_cursos_habilidades_views.xml',
        'views/trabajadores_educacion_views.xml',
        'views/trabajadores_educacion_tipos_views.xml',
        'views/trabajadores_educacion_tipos_certificacion.xml',
        'views/trabajadores_organigrama_views.xml',
        'views/trabajadores_equipo_tecnico_views.xml',
        'views/trabajadores_cargos_views.xml',
        'views/trabajadores_claves_horas_views.xml',
        'views/trabajadores_vacunacion_views.xml',
        'views/trabajadores_instruciones_views.xml',
        'views/trabajadores_seguridad_proteccion_views.xml',
        'views/trabajadores_seguridad_trabajador_views.xml',
        'views/trabajadores_tallas_views.xml',
        'views/trabajadores_cierre_views.xml',
        'views/trabajadores_cierre_historial_views.xml',
        'views/trabajadores_notificacion_cierre_views.xml',
        'views/trabajadores_areas_altas_bajas_views.xml',
        'views/trabajadores_areas_totales_views.xml',
        'views/calendar_trabajadores_views.xml',
        'data/etiquetas_data.xml',
        'data/familiar_data.xml',
        'data/disciplinaria_tipos_data.xml',
        'data/tipo_documento_data.xml',
        'data/educacion_tipo_data.xml',
        'data/certificadores_data.xml',
        'data/cursos_data.xml',
        'data/plantillas_correo_data.xml',
        'data/cron_automatizacion.xml',
        'data/tallas_data.xml',
        'report/trabajadores_report_views.xml',
        'informes/informe_medida_desciplinaria_views.xml',
        'wizard/trabajadores_cierre_wizard_views.xml',
        'wizard/trabajadores_dialog_wizard_views.xml',
        'views/trabajadores_menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sicpro_app_trabajadores/static/src/scss/hr.scss',
            'sicpro_app_trabajadores/static/src/scss/trabajadores.scss',
            'sicpro_app_trabajadores/static/src/scss/cursos_educacion.scss',
            'sicpro_app_trabajadores/static/src/scss/organigrama_chart.scss',
            'sicpro_app_trabajadores/static/src/js/resume_widget.js',
            'sicpro_app_trabajadores/static/src/scss/grafica_organizacional.scss',
            'sicpro_app_trabajadores/static/src/js/grafica_organizacional.js',
            'sicpro_app_trabajadores/static/src/js/organigrama_chart.js',
            'sicpro_app_trabajadores/static/src/js/cierre_mensual.js',
                               ],
        'web._assets_primary_variables': [
            'sicpro_app_trabajadores/static/src/scss/variables.scss'
        ],
        'web.assets_qweb': [
            'sicpro_app_trabajadores/static/src/xml/educacion_templates.xml',
            'sicpro_app_trabajadores/static/src/xml/cursos_templates.xml',
            'sicpro_app_trabajadores/static/src/xml/grafica_organizacional.xml',
            'sicpro_app_trabajadores/static/src/xml/organigrama.xml',
            'sicpro_app_trabajadores/static/src/xml/cierre_mensual.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_check',
    # 'post_init_hook': 'post_init_hook',
    # 'uninstall_hook': 'uninstall_hook',
}
