# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Trabajadores',
    'version': '1.0',
    'category': 'Trabajadores',
    'sequence': 2,
    'summary': "Esta aplicación se encargará del control de los datos "
               "de los trabajadores.",
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'website': 'https://www.facebook.com/danielbarreroreyes.oficial/',
    'license': 'AGPL-3',
    'depends': [
        'nucleo_sicpro_erp',
        'base',
        'mail',
        'resource',
        'sicpro_app_administracion',
        'sicpro_modulo_nomencladores',
        'smile_base_automation',
        'smile_log',
    ],
    'data': [
        'security/trabajadores.xml',
        'security/ir.model.access.csv',
        'views/trabajadores_ocupacion_views.xml',
        'views/trabajadores_categorias_views.xml',
        'views/trabajadores_templates.xml',
        'views/res_user.xml',
        'views/trabajadores_familiar_views.xml',
        'views/trabajadores_views.xml',
        'views/trabajadores_areas_views.xml',
        'views/trabajadores_tipo_documento_view.xml',
        'views/trabajadores_plantillas_documentos_views.xml',
        'views/trabajadores_documentos_view.xml',
        'views/trabajadores_disciplinaria_categorias_view.xml',
        'views/trabajadores_disciplinarias_acciones.xml',
        'views/trabajadores_cursos_habilidades_views.xml',
        'views/trabajadores_educacion_views.xml',
        'views/trabajadores_educacion_tipos_views.xml',
        'views/trabajadores_educacion_tipos_certificacion.xml',
        'views/trabajadores_organigrama_views.xml',
        'views/trabajadores_equipo_tecnico_views.xml',
        'views/trabajadores_cargos_views.xml',
        'views/trabajadores_claves_horas_views.xml',
        'views/trabajadores_vacunacion_views.xml',
        'views/trabajadores_instruciones_views.xml',
        'views/trabajadores_seguridad_proteccion_views.xml',
        'views/trabajadores_seguridad_trabajador_views.xml',
        'views/trabajadores_tallas_views.xml',
        'data/etiquetas_data.xml',
        'data/familiar_data.xml',
        'data/disciplinaria_tipos_data.xml',
        'data/tipo_documento_data.xml',
        'data/educacion_tipo_data.xml',
        'data/certificadores_data.xml',
        'data/cursos_data.xml',
        'data/plantillas_correo_data.xml',
        'data/cron_automatizacion.xml',
        'data/tallas_data.xml',
        'report/trabajadores_report_views.xml',
        'informes/informe_medida_desciplinaria_views.xml',
        'views/trabajadores_menu_views.xml',
    ],
    'qweb': ['static/src/xml/educacion_templates.xml',
             'static/src/xml/cursos_templates.xml',
             'static/src/xml/grafica_organizacional.xml',
             'static/src/xml/organigrama.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
