# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Metrología',
    'version': '1.0',
    'sequence': 2,
    'category': 'Productividad',
    'summary': "Esta aplicación se encargara de todo el control de los "
               "instrumentos de medición de la división.",
    'website': 'https://www.facebook.com/danielbarreroreyes.oficial/',
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'license': 'AGPL-3',
    'depends': ['nucleo_sicpro_erp',
                'base',
                'mail',
                'sicpro_modulo_nomencladores',
                'sicpro_app_trabajadores'],
    'data': [
        'security/metrologia.xml',
        'security/ir.model.access.csv',
        'views/metrologia_templates.xml',
        'views/mail_activity_views.xml',
        'views/metrologia_categorias_views.xml',
        'views/metrologia_estado_tecnico_views.xml',
        'views/metrologia_equipos_procesos_views.xml',
        'views/metrologia_centro_calibracion_views.xml',
        'views/metrologia_magnitudes_views.xml',
        'views/metrologia_equipamientos_views.xml',
        'data/metrologia_estados_tecnico_data.xml',
        'data/metrologia_centro_calibracion_data.xml',
        'views/metrologia_plan_calibracion_views.xml',
        'views/metrologia_todos_equipos_views.xml',
        'views/metrologia_registro_magnitudes_views.xml',
        'data/cron_automatizacion.xml',
        'data/plantillas_correo_data.xml',
        'views/metrologia_trabajadores_views.xml',
        'views/metrologia_dashboard_equipos_views.xml',
        'views/metrologia_menu_views.xml',
    ],
    'installable': True,
    'application': True,
}
