# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Fuerzas y Medios',
    'version': '1.0.0',
    # Estados (Desarrollo o Producción) Desarrollo: Store o actualiza Producción: Store avisa de nueva actualización
    'estado': 'Desarrollo',
    'sequence': 2,
    'category': 'Ordenes',
    'summary': "Esta aplicación se encarga de la gestión y control de la ubicación del personal de trabajo.",
    'website': 'https://www.facebook.com/dannyroses.oficial/',
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'price': 0,
    'currency': 'CUP',
    'company': 'División de Proyectos y Ejecución de Obras',
    'license': 'AGPL-3',
    # 'external_dependencies': {'python': ['nombre del paquete', 'nombre del paquete']},
    'depends': [
        'nucleo_sicpro_erp',
        'base',
        'calendar',
        'sicpro_app_clientes',
        'sicpro_app_ordenes_trabajo',
        'sicpro_app_transporte',
        'sicpro_modulo_dashboard_extendido',
    ],
    'data': [
        'security/fuerzas_medios.xml',
        'security/ir.model.access.csv',
        'data/etiquetas_data.xml',
        'data/estados_data.xml',
        # 'data/plantillas_correo_data.xml',
        # 'data/causa_paralizacion_data.xml',
        'views/fuerzas_medios_estados_views.xml',
        'views/fuerzas_medios_etiquetas_views.xml',
        'views/fuerzas_medios_views.xml',
        'views/fuerzas_medios_menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [],
        'web.assets_qweb': [], },
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_check',
    # 'post_init_hook': 'post_init_hook',
    # 'uninstall_hook': 'uninstall_hook',
}
