# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Firma Digital',
    'version': '1.0.0',
    # Estados (Desarrollo o Producción) Desarrollo: Store o actualiza Producción: Store avisa de nueva actualización
    'estado': 'Desarrollo',
    'summary': "Gestión del proceso de firma digital",
    'description': "Aquí esta recogida la configuración de la firma digital de los documentos",
    'category': 'Administración',
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'price': 0,
    'currency': 'CUP',
    'website': "https://www.facebook.com/dannyroses.oficial/",
    'license': 'AGPL-3',
    'sequence': 3,
    # 'external_dependencies': {'python': ['nombre del paquete', 'nombre del paquete']},
    'depends': [
        'base', 'web',
        'nucleo_sicpro_erp',
        'sicpro_app_administracion',
        'sicpro_modulo_certificados_digitales'
    ],
    "data": [
        'security/firma.xml',
        'security/ir.model.access.csv',
        "views/users_view.xml",
        "views/firma_etiquetas_views.xml",
        "views/firma_documentos_views.xml",
        "views/firma_documentos_firmado_views.xml",
        "wizard/documentos_wizard_views.xml",
        "wizard/firmar_wizard_views.xml",
        "wizard/subir_pdf_view.xml",
        "data/etiquetas_data.xml",
        "views/firma_menu_views.xml",
    ],
    'assets': {
        'web.assets_backend': [
            'sicpro_app_firma_digital/static/src/scss/pdf_cropper.scss',
            'sicpro_app_firma_digital/static/src/js/firma_widget.js',
            'sicpro_app_firma_digital/static/src/js/firma_nombre_widget.js',
            'sicpro_app_firma_digital/static/src/js/firma_dialog.js',
            'sicpro_app_firma_digital/static/src/js/pdf_cropper_viewer.js',
            'sicpro_app_firma_digital/static/src/js/image_processing.js',
            'sicpro_app_firma_digital/static/src/js/pdf_crop_widget.js',
            'sicpro_app_firma_digital/static/src/js/pdf_crop.js',
            'sicpro_app_firma_digital/static/src/js/subir_pdf_tree.js',
            'sicpro_app_firma_digital/static/src/js/subir_pdf_kanban.js',
            'sicpro_app_firma_digital/static/src/js/botones_control_firma.js',
        ],
        'web.assets_qweb': [
            'sicpro_app_firma_digital/static/src/xml/firma.xml',
            'sicpro_app_firma_digital/static/src/xml/templates_pdf_crop.xml',
            'sicpro_app_firma_digital/static/src/xml/pdf_cropper_viewer.xml',
            'sicpro_app_firma_digital/static/src/xml/subir_pdf_tree.xml',
            'sicpro_app_firma_digital/static/src/xml/subir_pdf_kanban.xml',
            'sicpro_app_firma_digital/static/src/xml/botones_control_firma.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_check',
    # 'post_init_hook': 'post_init_hook',
    # 'uninstall_hook': 'uninstall_hook',
}