# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Transferencias de Gastos',
    'version': '1.0.0',
    # Estados (Desarrollo o Producción) Desarrollo: Store o actualiza Producción: Store avisa de nueva actualización
    'estado': 'Desarrollo',
    'sequence': 2,
    'category': 'Ordenes',
    'summary': "Esta aplicación se encarga de gestión y control de las transferencias de gastos generados por los"
               " procesos claves de la ejecución.",
    'website': 'https://www.facebook.com/dannyroses.oficial/',
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'price': 0,
    'currency': 'CUP',
    'company': 'División de Proyectos y Ejecución de Obras',
    'license': 'AGPL-3',
    # 'external_dependencies': {'python': ['nombre del paquete', 'nombre del paquete']},
    'depends': [
        'nucleo_sicpro_erp',
        'sicpro_app_administracion',
        'base',
        'calendar',
        'sicpro_app_clientes',
        'sicpro_app_solicitudes',
        'sicpro_app_ordenes_trabajo',
        'sicpro_modulo_dashboard_extendido',
        'sicpro_modulo_one2many_search',
    ],
    'data': [
        'security/transferencias.xml',
        'security/ir.model.access.csv',
        'data/plantillas_correo_data.xml',
        'data/estados_gastos_ordenes_data.xml',
        'data/cuenta_gastos_data.xml',
        'data/morosidad_data.xml',
        'data/cron_automatizacion.xml',
        'wizard/transferencias_ordenes_views.xml',
        'wizard/transferencias_ajustes_views.xml',
        'wizard/transferencias_certificar_views.xml',
        'wizard/transferencias_gastos_cj74_views.xml',
        'wizard/transferencias_ordenes_rechazo_views.xml',
        'views/transferencias_ajustes_historial_views.xml',
        'views/transferencias_cuentas_gastos_views.xml',
        'views/transferencias_gastos_importar_views.xml',
        'views/transferencias_gastos_views.xml',
        'views/transferencias_ordenes_gastos_views.xml',
        'views/transferencias_ordenes_estados_views.xml',
        'views/transferencias_ordenes_morosidad_views.xml',
        'informes/dinamica_periodo_clase_coste_view.xml',
        'informes/dinamica_contabilizado_view.xml',
        'informes/dinamica_pendiente_contabilizar_view.xml',
        'informes/dinamica_pendiente_procesos_view.xml',
        'informes/informe_modelo_transferencia_gastos.xml',
        'views/ordenes_trabajo_views.xml',
        'views/transferencias_menu_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            '/sicpro_app_transferencias_gastos/static/src/js/transferir_subir_gastos_cj74.js',
            '/sicpro_app_transferencias_gastos/static/src/js/certificar_gastos_cj74.js',
        ],
        'web.assets_qweb': [
            'sicpro_app_transferencias_gastos/static/src/xml/transferir_subir_gastos_cj74.xml',
            'sicpro_app_transferencias_gastos/static/src/xml/certificar_gastos_cj74.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_check',
    # 'post_init_hook': 'post_init_hook',
    # 'uninstall_hook': 'uninstall_hook',
}
