# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Soporte',
    'version': '1.0',
    'sequence': 2,
    'category': 'Administración',
    'summary': "Esta aplicación se encargara de la gestión del "
               "soporte técnico de la administración del sistema.",
    'website': 'https://www.facebook.com/danielbarreroreyes.oficial/',
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'license': 'AGPL-3',
    'depends': [
        'mail',
        'portal',
        'sicpro_app_administracion',
        'sicpro_modulo_roles',
    ],
    'data': [
        'security/soporte_security.xml',
        'security/ir.model.access.csv',
        'views/res_partner_view.xml',
        'views/soporte_equipos_view.xml',
        'views/soporte_estados_view.xml',
        'views/soporte_estados_versiones_view.xml',
        'views/soporte_estados_paquetes_view.xml',
        'views/soporte_estados_aplicaciones_view.xml',
        'views/soporte_categoria_view.xml',
        'views/soporte_canales_view.xml',
        'views/soporte_etiquetas_view.xml',
        'views/soporte_ticket_view.xml',
        'views/soporte_dashboard_view.xml',
        'views/soporte_versiones_view.xml',
        'views/soporte_aplicaciones_view.xml',
        'views/soporte_paquetes_view.xml',
        'views/soporte_bitacora_view.xml',
        'data/equipos_data.xml',
        'data/plantillas_correo_data.xml',
        'data/soporte_data.xml',
        'data/categorias_data.xml',
        'data/etiquetas_data.xml',
        'data/estados_tickets_data.xml',
        'data/canales_data.xml',
        'data/estados_versiones_data.xml',
        'data/estados_aplicaciones_data.xml',
        'data/estados_paquetes_data.xml',
        'views/soporte_ticket_menu.xml',
    ],

    'application': True,
    'installable': True,
}
