# -*- coding: utf-8 -*-

{
    'name': 'SICPRO: Soporte',
    'version': '1.0.0',
    # Estados (Desarrollo o Producción) Desarrollo: Store o actualiza Producción: Store avisa de nueva actualización
    'estado': 'Desarrollo',
    'sequence': 2,
    'category': 'Administración',
    'summary': "Esta aplicación se encargara de la gestión del "
               "soporte técnico de la administración del sistema.",
    'website': 'https://www.facebook.com/dannyroses.oficial/',
    'author': 'Daniel Barrero Reyes',
    'support': 'daniel.borrero@etecsa.cu',
    'price': 0,
    'currency': 'CUP',
    'license': 'AGPL-3',
    # 'external_dependencies': {'python': ['nombre del paquete', 'nombre del paquete']},
    'depends': [
        'base',
        'mail',
        'sicpro_app_trabajadores',
        'nucleo_sicpro_erp',
        'sicpro_modulo_roles',
        'sicpro_modulo_dominio_dinamico',
    ],
    'data': [
        'security/soporte_security.xml',
        'security/ir.model.access.csv',
        'views/trabajadores_view.xml',
        'views/soporte_equipos_view.xml',
        'views/soporte_estados_view.xml',
        'views/soporte_estados_versiones_view.xml',
        'views/soporte_estados_paquetes_view.xml',
        'views/soporte_estados_aplicaciones_view.xml',
        'views/soporte_etiquetas_view.xml',
        'views/soporte_canales_view.xml',
        'views/soporte_etiquetas_view.xml',
        'views/soporte_ticket_view.xml',
        'views/soporte_ticket_todos_view.xml',
        'views/soporte_dashboard_view.xml',
        'views/soporte_versiones_view.xml',
        'views/soporte_aplicaciones_view.xml',
        'views/soporte_paquetes_view.xml',
        'views/soporte_bitacora_view.xml',
        'views/soporte_fragmentos_codigos_view.xml',
        'views/soporte_cronograma_plan_view.xml',
        'views/soporte_cronograma_anios_view.xml',
        'data/equipos_data.xml',
        'data/plantillas_correo_data.xml',
        'data/soporte_data.xml',
        'data/etiquetas_data.xml',
        'data/estados_tickets_data.xml',
        'data/canales_data.xml',
        'data/estados_versiones_data.xml',
        'data/estados_aplicaciones_data.xml',
        'data/estados_paquetes_data.xml',
        'views/soporte_ticket_menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            # Librería GANTT
            "sicpro_app_soporte/static/lib/dhtmlxgantt/js/dhtmlxgantt.js",
            "sicpro_app_soporte/static/lib/dhtmlxgantt/js/dhtmlxgantt_marker.js",
            "sicpro_app_soporte/static/lib/dhtmlxgantt/css/dhtmlxgantt.css",
            "sicpro_app_soporte/static/lib/dhtmlxgantt/skins/dhtmlxgantt_broadway.css",
            # Conectores internos con la librería
            "sicpro_app_soporte/static/src/js/gantt_model.js",
            "sicpro_app_soporte/static/src/js/gantt_renderer.js",
            "sicpro_app_soporte/static/src/js/gantt_controller.js",
            "sicpro_app_soporte/static/src/js/gantt_view.js",
            "sicpro_app_soporte/static/src/js/gantt_action.js",
            "sicpro_app_soporte/static/src/css/gantt.css",
        ],
        'web.assets_frontend': [],
        'web.assets_qweb': [
            'sicpro_app_soporte/static/src/xml/soporte_gantt.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'pre_init_hook': 'pre_init_check',
    # 'post_init_hook': 'post_init_hook',
    # 'uninstall_hook': 'uninstall_hook',
}
